config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'signup' , to: 'users#signup'
  get 'displaycredentials' , to: 'welcome#displaycredentials'
  
  
  
  resources :credentials
  get 'signup' , to: 'users#signup'
  resources :users, except: [:new,:show]
  get 'users/:id/search' , to: 'users#search' , as: 'search_user'
  get 'users/:id/viewBooks' , to: 'users#viewBooks' , as: 'viewBooks_user'
  get 'users/:id/results' , to: 'users#results' , as: 'results_user'
  get '/users/:id/:bookid' => 'users#selectbook', :as => :selectbook
  get '/users/:id/:booklogid/returnbook' => 'users#returnbook', :as => :returnbook
  #resources :credentials
  resources :admins, except: [:new,:show]

  get '/admins/:id' , to: 'admins#adminhome'
  get 'admins/:id/search' , to: 'admins#search' , as: 'search_admin'
  get 'admins/:id/results' , to: 'admins#results' , as: 'results_admin'
  get '/admins/:bookid' => 'admins#editbook', :as => :editbook
  get 'admins/:id/searchuser' , to: 'admins#searchuser' , as: 'searchuser_admin'
  get 'admins/:id/resetpassword' , to: 'admins#resetpassword' , as: 'resetpassword_admin'
  get 'admins/:id/userresults' , to: 'admins#userresults' , as: 'userresults_admin'
  get 'admins/:id/recreateuser' , to: 'admins#recreateuser' , as: 'recreateuser_admin'
  get 'admins/:id/createuser' , to: 'admins#createuser' , as: 'createuser_admin'
  post 'admins/:id/saveuser' , to: 'admins#saveuser' , as: 'saveuser_admin'
  patch 'credentials/:id' , to: 'credentials#update'
  
  resources :books
  get '/books/:id/new', to: 'books#create'

  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  get '/users/:id' , to: 'users#userhome'

  # patch 'users/editpassword/:id' , to: 'users#updatepassword'
  # put 'users/editpassword/:id' , to: 'users#updatepassword'
  #post '/credentials/:id/edit' , to: 'credentials#edit'
  delete 'logout', to: 'sessions#destroy'
end

app/views/admins/adminhome.html.erb
<% if logged_in?%>
<strong></Bold>Hello <%= current_user.fname%></strong></br></br>

<div class="btn-group float_btn" role="group">
<p><%= link_to 'Add Books', book_path, class: "btn btn-xlg btn-info" %><p/>
</div>

<div class="btn-group float_btn" role="group">
<p><%= link_to 'Log out', logout_path, class: "btn btn-xlg btn-info", method: :delete %><p/>
</div>

<div class="btn-group float_btn" role="group">
<p><%= link_to 'Edit Profile', edit_admin_path(@user) , class: "btn btn-xlg btn-info"%></p>
</div>


<%else%>
<% redirect_to login_path%>
<%  end%>

app/views/admins/createuser.html.erb
<%= render 'shared/errors', obj: @user %>
<%= render 'shared/errors', obj: @cred %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
<%= link_to 'Back', root_path %>

<%= form_for @user , :url => saveuser_admin_path do |f| %>
<%= f.label :fname ,'First Name' , autofocus: true%><br/>
  <%= f.text_field :fname, class: 'form-control'  %>
</br>

<%= f.label :lname , 'Last Name' %><br/>
  <%= f.text_field :lname, class: 'form-control'  %>
</br>

<%= f.label :email ,'Email'%><br/>
  <%= f.email_field :email, class: 'form-control'  %>
</br>

  <%= f.label :username , 'Username'%><br/>
  <%= f.text_field :username, class: 'form-control'  %>
</br>

<%= f.label :userType ,'User Type'%><br/>
<%= f.select :userType, [['User Type','select'],['Admin','admin'],['User','user']] , class: "btn btn-primary btn-block" %>
</br>  </br>  

  <%= f.submit "Create" , class: "btn btn-primary btn-block" %>

<% end %>

 </div>
</div>

app/views/admins/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
    <%= link_to 'Back', root_path %></br></br>
    
    <%= form_for @user do |f| %>

<%= f.label :fname ,'First Name' , autofocus: true%><br/>
  <%= f.text_field :fname , class: 'form-control' %>
</br>

<%= f.label :lname , 'Last Name' %><br/>
  <%= f.text_field :lname , class: 'form-control' %>
</br>

<%= f.label :email ,'Email'%><br/>
  <%= f.email_field :email , class: 'form-control' %>
</br>

Want to edit password? <%= link_to 'Edit password', edit_credential_path(@user)%>
<%= f.submit "Edit", class: "btn btn-primary btn-block"  %>

<% end %>

  </div>
</div>

app/views/admins/editbook.html.erb
<br>
<%= form_for(@book) do |f| %>
  <%= render 'shared/errors', obj: @book %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, ["--Select--",'available', 'Coming Soon']%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/editpassword.html.erb
<%= link_to 'Home', root_path %>
<p><%= link_to 'Back', edit_user_path(@user)%></p>
<H2>Edit Password here<h2>
  
 
 
<%= form_for :user do |f| %>
<p><%= f.label :password ,'password' , autofocus: true%><br/>
  <%= f.password_field :password %>
</p>
<p><%= f.label :newpassword , 'New password' %><br/>
  <%= f.password_field :newpassword %>
</p>
<p><%= f.label :repeatnewpassword ,'re-enter password'%><br/>
  <%= f.password_field :repeatnewpassword %>
</p>
<p>
  <%= f.submit %>
 </p>
 <%end%>

app/views/admins/results.html.erb
<% if logged_in?%>

<%= link_to 'Back', search_admin_path(@user)%></p>

 <h2><em>Search Results for: </em><%= @searchtype%> <font size=6>"<%= @keyWord%>"</font></h2>
 <%if !@books.empty?%>
 <table class="table">
     
    <thead>
    <tr>
      <th>Book ID</th>
  		<th>Book Name</th>
	    <th>Author</th>
	    <th>availability</th>
	    
	    <th colspan="3"></th>
  </tr>
  </thead>
  
 <% @books.each do |book| %>
 <tbody>
 
 <tr>
  <td> <%= book.id %></td>
 <td> <%= book.title %></td>
  <td><%= book.author %></td>
  <td><%= book.status %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %> |
    <%= link_to 'Delete Book', book,controller: :book , method: :delete, data: { confirm: 'Are you sure?' } %></td>

<% end %>
</tr>
</tbody>
</table>
  <%else%>
  No Results found
 <%end%>
<%else%>
<% redirect_to login_path%>
<%  end%>

app/views/admins/search.html.erb
<% if logged_in?%>
<p><%= link_to 'Back', user_path %> |
<%= link_to 'Log out', logout_path, method: :delete %> |
<%= link_to 'Edit Profile', edit_admin_path(@user)%></p>

<div class='row'>
    <div class='col-xs-12'>
          
<%= form_tag(results_admin_path, method: "get") do %>
      <%= label_tag(:q, "Keyword:") %>
      <%= text_field_tag(:keyWord) %><br>
      <%= radio_button_tag(:searchtype, "title", checked = true) %>
      <%= label_tag(:title, "Book Title") %>
      <%= radio_button_tag(:searchtype, "author") %>
      <%= label_tag(:author, "Author") %>
      <%= radio_button_tag(:searchtype, "category" ) %>
      <%= label_tag(:category, "category" ) %></br>
      <%= submit_tag("Search")%>
<% end %>
<%else%>
<% redirect_to login_path%>
<%  end%>

      </div>

</div>

app/views/admins/searchuser.html.erb
<% if logged_in?%>
<p><%= link_to 'Back', user_path %> |
<%= link_to 'Log out', logout_path, method: :delete %> |
<%= link_to 'Edit Profile', edit_admin_path(@user)%></p>

<div class='row'>
    <div class='col-xs-12'>
          
<%= form_tag(userresults_admin_path, method: "get") do %>
      <%= label_tag(:q, "Keyword:") %>
      <%= text_field_tag(:keyWord) %><br>
      <%= radio_button_tag(:searchtype, "fname", checked = true) %>
      <%= label_tag(:title, "First Name") %>
      <%= radio_button_tag(:searchtype, "lname") %>
      <%= label_tag(:author, "Last Name") %>
      <%= radio_button_tag(:searchtype, "username" ) %>
      <%= label_tag(:category, "Username" ) %></br>
      <%= submit_tag("Search")%>
<% end %>
<%else%>
<% redirect_to login_path%>
<%  end%>

      </div>

</div>

app/views/admins/userresults.html.erb
<% if logged_in?%>

<%= link_to 'Back', searchuser_admin_path(@user)%></p>

 <h2><em>Search Results for: </em><%= @searchtype%> <font size=6>"<%= @keyWord%>"</font></h2>
 <%if !@users.empty?%>
 <table class="table">
     
    <thead>
    <tr>
      <th>First Name</th>
  		<th>Last Name</th>
	    <th>Email</th>
	    <th>User Name</th>
	    <th>Number of Books taken</th>
	    <th colspan="3"></th>
  </tr>
  </thead>
  
 <% @users.each do |user| %>
 <tbody>
 
 <tr>
  <td> <%= user.fname %></td>
 <td> <%= user.lname %></td>
  <td><%= user.email %></td>
  <td><%= user.username %></td>
  <td><%= Booklog.where("user_id = ? AND returned IS ?", user.id, nil).count %></td>
  <% if Credential.exists?(user_id: user.id) %>
    <td><%= link_to 'Reset Password', resetpassword_admin_path(user) %> |
    <% cred=Credential.find_by(user_id: user.id)%>
    <%= link_to 'Delete User', cred ,controller: :credential , method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <%else%>
    <td>User Already Deleted |
    <%= link_to 'Re-Create', recreateuser_admin_path(user) %> 
    </td>
  <% end %>
<% end %>
</tr>
</tbody>
</table>
  <%else%>
  No Results found
 <%end%>
<%else%>
<% redirect_to login_path%>
<%  end%>