config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'signup' , to: 'users#signup'
  get 'displaycredentials' , to: 'welcome#displaycredentials'
  
  
  
  resources :credentials
  get 'signup' , to: 'users#signup'
  resources :users, except: [:new,:show]
  get 'users/:id/search' , to: 'users#search' , as: 'search_user'
  get 'users/:id/viewBooks' , to: 'users#viewBooks' , as: 'viewBooks_user'
  get 'users/:id/results' , to: 'users#results' , as: 'results_user'
  get '/users/:id/:bookid' => 'users#selectbook', :as => :selectbook
  get '/users/:id/:booklogid/returnbook' => 'users#returnbook', :as => :returnbook
  #resources :credentials
  resources :admins, except: [:new,:show]

  get '/admins/:id' , to: 'admins#adminhome'
  get 'admins/:id/search' , to: 'admins#search' , as: 'search_admin'
  get 'admins/:id/results' , to: 'admins#results' , as: 'results_admin'
  get '/admins/:bookid' => 'admins#editbook', :as => :editbook
  get 'admins/:id/searchuser' , to: 'admins#searchuser' , as: 'searchuser_admin'
  get 'admins/:id/resetpassword' , to: 'admins#resetpassword' , as: 'resetpassword_admin'
  get 'admins/:id/userresults' , to: 'admins#userresults' , as: 'userresults_admin'
  get 'admins/:id/recreateuser' , to: 'admins#recreateuser' , as: 'recreateuser_admin'
  get 'admins/:id/createuser' , to: 'admins#createuser' , as: 'createuser_admin'
  post 'admins/:id/saveuser' , to: 'admins#saveuser' , as: 'saveuser_admin'
  patch 'credentials/:id' , to: 'credentials#update'
  
  resources :books
  get '/books/:id/new', to: 'books#create'

  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  get '/users/:id' , to: 'users#userhome'

  # patch 'users/editpassword/:id' , to: 'users#updatepassword'
  # put 'users/editpassword/:id' , to: 'users#updatepassword'
  #post '/credentials/:id/edit' , to: 'credentials#edit'
  delete 'logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :userType
  has_one :credential
  has_and_belongs_to_many :books
  before_save{self.email=email.downcase}
  validates :fname, presence: true, 
            length: {minimum: 3, maximum: 20, }
  validates :lname, presence: true, 
            length: {minimum: 3, maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 5, maximum: 25}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #check for session before direction to pages
  #before_action :set_cred, only:[:editpassword]
  before_action :set_user, except:[:signup, :create]
  before_action :require_user , only: [:edit,:userhome,:editpassword, :updatepassword, :viewBooks, :selectbook , :returnbook]
  before_action :require_same_user , only: [:edit,:editpassword, :viewBooks , :selectbook, :returnbook]
  def signup
    @cred=Credential.new
    @user=User.new
  end
  
  def create
    @user = User.new(users_params)
    @cred=Credential.new(user: @user, username: @user.username , password: params[:password], userType: 'user')
    @userType="user";
    # if Credential.find_by(loginId: "")
    #   flash[:notice] = "Username already exist"
    #   render 'signup'
    # end
    if @user.valid? && @cred.valid?
      @cred=Credential.new(user: @user, username: @user.username , password: params[:password], userType: 'user')
      @user.save
      @cred.save
      flash[:success] = "Account successfully created"
      redirect_to root_path(@user)
    else
      render 'signup'
    end
  end
  
  def edit
    @cred=Credential.find_by(username: @user.username)
  end
  
  def update
    @user.update(users_params)
    if @user.save
      flash[:success] = "Your profile has been successfully updated  "
      if Credential.find_by(user_id: @user.id).userType=='user'
        redirect_to user_path(@user)
      else
        redirect_to admin_path(@user)
      end
    else
      render 'edit'
    end
  end
  
  def search
  
  end
  
  def viewBooks
    # update the below to display current borrowed books
    @borrowedlog=Booklog.where("user_id = ? AND returned IS ?", @user.id, nil)
    # @booksBorrowed=Booklog.find_by(user_id: @user.id)
  end
  
  def results
    # update the below to display search results
    @keyWord=params['keyWord'];
    if(@keyWord=='')
    flash[:success] = "Enter a keyword to search"
    redirect_to search_user_path(@user)
    end
    @searchtype=params['searchtype'];
    if(@searchtype=="title")
        @books=Book.where('title LIKE ?',"%#{@keyWord}%")
      elsif(@searchtype=="author")
        @books=Book.where('author LIKE ?',"%#{@keyWord}%")
      else
        @books=Book.where('category LIKE ?', "%#{@keyWord}%")
    end
  end
  
  def selectbook
    @book=Book.find(params[:bookid])
    @book.status="unavailable"
    @book.save
    @booklog=Booklog.create(user_id: @user.id, book_id: @book.id, borrowed: Time.now)
    flash[:success] = "Book Added"
    redirect_to user_path(@user)
  end
  
  def returnbook
    @booklog=Booklog.find(params[:booklogid])
    @booklog.returned=Time.now
    @booklog.save
    @book=Book.find(@booklog.book_id)
    @book.status="available"
    @book.save
    flash[:success] = "Book Returned"
    redirect_to user_path(@user)
  end
  
  def userhome
    #The user home after login Page
  end
  
  private
    def users_params
        params.require(:user).permit(:fname, :lname, :email, :username)
    end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def set_cred
    @cred= Credential.find_by(username: @user.username)
  end
  
  def require_same_user
    if current_user != @user
      flash[:danger] = "You can only edit your profile"
      redirect_to root_path
    end
  end
  
end

app/views/users/edit.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user do |f| %>


<%= f.label :fname ,'First Name' , autofocus: true%><br/>
  <%= f.text_field :fname , class: 'form-control' %>
</br>

<%= f.label :lname , 'Last Name' %><br/>
  <%= f.text_field :lname , class: 'form-control' %>
</br>

<%= f.label :email ,'Email'%><br/>
  <%= f.email_field :email , class: 'form-control' %>
</br>

Want to edit password? <%= link_to 'Edit password', edit_credential_path(@user)%>
<%= f.submit "Edit", class: "btn btn-primary btn-block"  %>

<% end %>

  </div>
</div>

app/views/users/editpassword.html.erb
<%= render 'shared/errors', obj: @user %>
<%= link_to 'Back', edit_user_path(@user)%>
 
<div class="row">
  <div class="col-md-6 col-md-offset-3"> 
 
<%= form_for :user do |f| %>

<%= f.label :password ,'password' , autofocus: true%><br/>
<%= f.password_field :password, class: 'form-control' %>
</br>

<%= f.label :newpassword , 'New password' %><br/>
  <%= f.password_field :newpassword, class: 'form-control' %>
  </br>

<%= f.label :repeatnewpassword ,'re-enter password'%><br/>
<%= f.password_field :repeatnewpassword, class: 'form-control' %>
</br>


  <%= f.submit "Change" , class: "btn btn-primary btn-block"%>
 
 <%end%>
 
  </div>
</div>

app/views/users/results.html.erb
<% if logged_in?%>

<p><%= link_to 'Log out', logout_path, method: :delete %> |
<%= link_to 'Edit Profile', edit_user_path(@user)%> |
<%= link_to 'Back', search_user_path(@user.id)%></p>

 <h2><em>Search Results for: </em><%= @searchtype%> <font size=6>"<%= @keyWord%>"</font></h2>
 <%if !@books.empty?%>
 <table class="table">
     
    <thead>
    <tr>
  		<th>Book Name</th>
	    <th>Author</th>
	    <th>availability</th>
	    
	    <th colspan="3"></th>
  </tr>
  </thead>
  
 <% @books.each do |book| %>
 <tbody>
 
 <tr>
 <td> <%= book.title %></td>
  <td><%= book.author %></td>
  <td><%= book.status %></td>
  <% if book.status== 'available'%>
    <td><%= link_to 'Add Book',
            {controller: 'users',
             action: 'selectbook',
             id: @user,
             bookid: book},
            class: 'button' %></td>
  <%else
    booklog=Booklog.find_by(book_id: book.id)
    if(!booklog.nil? && booklog.user_id==@user.id)%>
    <td>Already selected</td>
    <%end%>
  <%end%>
  
<% end %>
</tr>
</tbody>
</table>
  <%else%>
  No Results found
 <%end%>
<%else%>
<% redirect_to login_path%>
<%  end%>

app/views/users/search.html.erb
<% if logged_in?%>
<p><%= link_to 'Back', user_path %> |
<%= link_to 'Log out', logout_path, method: :delete %> |
<%= link_to 'Edit Profile', edit_user_path(@user)%></p>

<div class='row'>
    <div class='col-xs-12'>
          
<%= form_tag(results_user_path, method: "get") do %>
      <%= label_tag(:q, "Keyword:") %>
      <%= text_field_tag(:keyWord) %><br>
      <%= radio_button_tag(:searchtype, "title", checked = true) %>
      <%= label_tag(:title, "Book Title") %>
      <%= radio_button_tag(:searchtype, "author") %>
      <%= label_tag(:author, "Author") %>
      <%= radio_button_tag(:searchtype, "category" ) %>
      <%= label_tag(:category, "category" ) %></br>
      <%= submit_tag("Search")%>
<% end %>
<%else%>
<% redirect_to login_path%>
<%  end%>

      </div>

</div>

app/views/users/show.html.erb
<% if logged_in?%>
<p><%= link_to 'Log out', logout_path, method: :delete %><p/>
Hello <%= current_user.fname%>
<%else%>
<%= link_to 'login', login_path%><p/>
<%  end%>

app/views/users/signup.html.erb
<%= render 'shared/errors', obj: @user %>
<%= render 'shared/errors', obj: @cred %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
<%= link_to 'Back', root_path %>

<%= form_for @user do |f| %>
<%= f.label :fname ,'First Name' , autofocus: true%><br/>
  <%= f.text_field :fname, class: 'form-control'  %>
</br>

<%= f.label :lname , 'Last Name' %><br/>
  <%= f.text_field :lname, class: 'form-control'  %>
</br>

<%= f.label :email ,'Email'%><br/>
  <%= f.email_field :email, class: 'form-control'  %>
</br>

  <%= f.label :username , 'Username'%><br/>
  <%= f.text_field :username, class: 'form-control'  %>
</br>

  <%= f.fields_for :cred do |e| %>
    <%= e.label :password, "password" %><br/>
    <%= password_field_tag :password, class: 'form-control'  %>
  <% end %>
  <!--<%= label_tag :password, 'password' %><br/>-->
  <!--<%= password_field_tag :password, class: 'form-control'  %>-->
</br>
</br>

  <%= f.submit "Sign-up" , class: "btn btn-primary btn-block" %>

<% end %>

 </div>
</div>

app/views/users/userhome.html.erb
<% if logged_in?%>
<strong></Bold>Hello <%= current_user.fname%></strong></br></br>

<div class="btn-group float_btn" role="group">
<p><%= link_to 'Log out', logout_path, class: "btn btn-xlg btn-info", method: :delete %><p/>
</div>

<div class="btn-group float_btn" role="group">
<p><%= link_to 'Edit Profile', edit_user_path(@user) , class: "btn btn-xlg btn-info"%></p>
</div>

<div class="btn-group float_btn" role="group">
<p><%= link_to 'search Book', search_user_path(@user.id), class: "btn btn-xlg btn-info"%></p>
</div>

<div class="btn-group float_btn" role="group">
<p><%= link_to 'view Book', viewBooks_user_path(@user.id), class: "btn btn-xlg btn-info"%></p>
</div>

<%else%>
<% redirect_to login_path%>
<%  end%>

app/views/users/viewBooks.html.erb
<% if logged_in?%>
<p><%= link_to 'Back', user_path %> |
<%= link_to 'Log out', logout_path, method: :delete %> |
<%= link_to 'Edit Profile', edit_user_path(@user)%></p>
<%if !@borrowedlog.empty?%>
  <table class="table">
    <thead>
    <tr>
      <th>Book Name</th>
	    <th>Author</th>
	    <th colspan="3"></th>
    </tr>
    </thead>
  <% @borrowedlog.each do |bookborrowed| 
    book=Book.find(bookborrowed.book_id)
    %>
    
<tbody>
    <tr>
      <td> <%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= link_to 'Return Book',
            {controller: 'users',
             action: 'returnbook',
             id: @user,
             booklogid: bookborrowed},
            class: 'button' %></td>
  <% end %>
  </tr>
  </tbody>
    </table>
<%else%>
  No pending Books 
<%end%>

<%else%>
<% redirect_to login_path%>
<%  end%>