config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'signup' , to: 'users#signup'
  get 'displaycredentials' , to: 'welcome#displaycredentials'
  
  
  
  resources :credentials
  get 'signup' , to: 'users#signup'
  resources :users, except: [:new,:show]
  get 'users/:id/search' , to: 'users#search' , as: 'search_user'
  get 'users/:id/viewBooks' , to: 'users#viewBooks' , as: 'viewBooks_user'
  get 'users/:id/results' , to: 'users#results' , as: 'results_user'
  get '/users/:id/:bookid' => 'users#selectbook', :as => :selectbook
  get '/users/:id/:booklogid/returnbook' => 'users#returnbook', :as => :returnbook
  #resources :credentials
  resources :admins, except: [:new,:show]

  get '/admins/:id' , to: 'admins#adminhome'
  get 'admins/:id/search' , to: 'admins#search' , as: 'search_admin'
  get 'admins/:id/results' , to: 'admins#results' , as: 'results_admin'
  get '/admins/:bookid' => 'admins#editbook', :as => :editbook
  get 'admins/:id/searchuser' , to: 'admins#searchuser' , as: 'searchuser_admin'
  get 'admins/:id/resetpassword' , to: 'admins#resetpassword' , as: 'resetpassword_admin'
  get 'admins/:id/userresults' , to: 'admins#userresults' , as: 'userresults_admin'
  get 'admins/:id/recreateuser' , to: 'admins#recreateuser' , as: 'recreateuser_admin'
  get 'admins/:id/createuser' , to: 'admins#createuser' , as: 'createuser_admin'
  post 'admins/:id/saveuser' , to: 'admins#saveuser' , as: 'saveuser_admin'
  patch 'credentials/:id' , to: 'credentials#update'
  
  resources :books
  get '/books/:id/new', to: 'books#create'

  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  get '/users/:id' , to: 'users#userhome'

  # patch 'users/editpassword/:id' , to: 'users#updatepassword'
  # put 'users/editpassword/:id' , to: 'users#updatepassword'
  #post '/credentials/:id/edit' , to: 'credentials#edit'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
      
      
        <small>
          Copyright &copy; 2016 <a href="#">CSC 620 Ruby Project</a>
          by <a href="#">Hemanth,</a>
             <a href="#">Andrew,</a>
             <a href="#">Thamer,</a>
             <a href="#">Ghazi</a>
        </small>
      
      
  </footer>
  
</div>

app/views/layouts/_messages.html.erb
<!-- To display the flash -->
<div class="row">

    <div class="col-xs-10 col-xs-offset-1">

    <% flash.each do |name, msg| %>

    <div class='alert alert-<%="#{name}" %>'>

    <a href="#" class="close" data-dismiss="alert">×</a>

    <%= content_tag :div, simple_format(msg), :id => "flash_#{name}" if msg.is_a?(String) %>

    </div>

    <% end %>

    </div>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
   <%= link_to "LMS", root_path, class: "navbar-brand", id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
      <%if Credential.find_by(user_id: current_user.id).userType=='admin'%>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%= createuser_admin_path(current_user.id)%>>Add User</a></li>
            <li><a href=<%= searchuser_admin_path(current_user.id)%>>Edit/Update User</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Books <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%= new_book_path(@user)%>>Add Book</a></li>
            <li><a href=<%= search_admin_path(current_user.id)%>>Edit/delete Book</a></li>
            <li><a href="#">Update Book Status</a></li>
          </ul>
        </li>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%= edit_admin_path(current_user)%>>Edit Profile</a></li>
            <li><a href=<%= edit_credential_path(current_user.id)%>>Edit Password</a></li>
          </ul>
        </li>
      <%else%>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Books <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%= viewBooks_user_path(current_user.id)%>>View Book</a></li>
            <li><a href=<%= search_user_path(current_user.id)%>>Search Book</a></li>
          </ul>
        </li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%= edit_user_path(@user)%>>Edit Profile</a></li>
            <li><a href=<%= edit_credential_path(current_user.id)%>>Edit Password</a></li>
          </ul>
        </li>
      <%end%>
      <li><%= link_to 'Log out', logout_path, method: :delete , class: "navbar-brand", style: "color: #ffffff" %></li>
      <%else%>
      <li><%= link_to 'Log in', login_path, class: "navbar-brand", style: "color: #ffffff" %></li>
      <%end%>
      </ul>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lms</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
  <!--Build navigation here -->
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
    
  <!--To have it contained in middle-->
  <div class='container'>
  <%= yield %>
  </div>
  <center>
  <%= render 'layouts/footer' %>
  </center>
  </body>
</html>